package com.sitescrape.writer;

import com.sitescrape.model.Article;

import java.io.IOException;
import java.util.List;


/**
 * Contract for writing articles generated by the external website reader.
 */
public interface PageWriter {
    public void writeArticles(List<Article> articles, String file) throws IOException;
}
